services:
  - type: web
    name: blog-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 